sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.071.1
 - ldc-1.1.0-beta3

env:
 - ARCH="x86_64"

matrix:
  include:
    - {os: linux, d: dmd-2.071.1, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.0.0, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}

branches:
  only:
    - master
    - stable

script:
 - echo "$ARCH"
 - dub test --arch "$ARCH" -b unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - devteam@mir.rocks

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2d7cb29fc776c5eaeef
    on_success: change
    on_failure: always
    on_start: never
